DROP DATABASE IF EXISTS reviews;
CREATE DATABASE reviews;

DROP TABLE IF EXISTS reviews_photos;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS characteristics_reviews;



CREATE TABLE reviews_photos (
  id INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  photo_url VARCHAR,
  review_id INT FOREIGN KEY
);


CREATE TABLE reviews (
  review_id INT PRIMARY KEY,
  product_id INT FOREIGN KEY,
  rating SMALLINT CHECK (rating > 0) (rating < 6),
  summary VARCHAR,
  recommend BOOLEAN,
  response VARCHAR,
  reported BOOLEAN,
  body VARCHAR,
  date_added,
  reviewer_name VARCHAR,
  reviewer_email VARCHAR,
  helpfulness INT
);

CREATE TABLE characteristics_reviews (
  id INT PRIMARY KEY,
  characteristic_id FOREIGN KEY,
  review_id FOREIGN KEY,
  value INT
);

-- CREATE TABLE meta (
--   product_id primary key
-- );

-- CREATE TABLE characteristics (

-- )