DROP DATABASE IF EXISTS reviews;
CREATE DATABASE reviews;

\c reviews;

DROP TABLE IF EXISTS photos CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS product_characteristics_join CASCADE;
DROP TABLE IF EXISTS characteristics_reviews CASCADE;

DROP TABLE IF EXISTS meta CASCADE;
DROP TABLE IF EXISTS characteristics CASCADE;

CREATE TABLE reviews (
  review_id INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  product_id INT NOT NULL, -- index this
  rating SMALLINT CHECK (rating > 0 AND rating < 6),
  date_unix BIGINT, -- in UNIX will have to reshape -- also drop
  summary VARCHAR(1000),
  body VARCHAR(800),
  recommend BOOLEAN,
  reported BOOLEAN DEFAULT false,
  reviewer_name VARCHAR(30),
  reviewer_email VARCHAR(40),
  response VARCHAR(800),
  helpfulness INT DEFAULT 0
) WITH (
  OIDS=FALSE
);

CREATE TABLE photos (
  id INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  review_id INT references reviews(review_id), -- index this
  photo_url VARCHAR(1000)
) WITH (
  OIDS=FALSE
);

CREATE TABLE product_characteristics_join (
  id INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  product_id INT, -- index this
  characteristic_name VARCHAR(15) -- drop this
  -- characteristic_id will reference characteristiccs
  -- total_score
  -- total_votes
) WITH (
  OIDS=FALSE
);

CREATE TABLE characteristics_reviews (
  id INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  old_characteristic_id INT, -- drop this
  review_id INT references reviews(review_id),
  value SMALLINT CHECK (value > 0 and value < 6)
  -- characteristic_id will reference characteristics
) WITH (
  OIDS=FALSE
);
